# Generated by Django 4.2.1 on 2023-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcentral', '0003_alter_event_opentodept'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
